Name (string)
Flavor text (string)
power (int)
isSingleTarget (0 or 1)
targetsEnemy (0 or 1)
statusToApply (NOSTATUS, DPT, SHIELD, INCAP)
statusPower (int)
attributeToAugment (NOATTRIBUTE, POWER, CURRENTPP, PPREGEN, ARMOR)
attributeMultiplier (double)